### PR TITLE
map sticks to the right

### PR DESCRIPTION
**Pull request by louiseleighhh**

### CODE REVIEW

**Comment by louiseleighhh** [comment]
Has a conflict with the branch I had a pull request because I changed a few codes while trying to put the map sticky to the right. **To the person merging this branch put the search feature code to the uppermost part of index.html.erb NOT inside any div classes**. I will handle adjustments to fit it with the latest design of my latest branch.

**Comment by sejess** [comment]
I don't know how to fix this. I tried moving the code for the search function to the top, but it didn't resolve the issue.

**Comment by louiseleighhh** [comment]
I fixed the conflict can you merge it now

**Comment by louiseleighhh** [comment]
And the other branch too 🙇🏻‍♀️

**Pull request merged**
